#!/bin/bash

LANG=en_US.utf-8
LANGUAGE=en
PROMETHEUS_HOST=$(ceph orch ps |grep prome | tr -s " " |cut -d " " -f 2)
GRAFANA_HOST=$(ceph orch ps |grep grafana | tr -s " " |cut -d " " -f 2)
ALERTMANAGER_HOST=$(ceph orch ps |grep alertmanager | tr -s " " |cut -d " " -f 2)

PROMETHEUS_IP=$(cat /etc/hosts | grep $PROMETHEUS_HOST-mngt | cut -d " " -f 1)
GRAFANA_IP=$(cat /etc/hosts | grep $GRAFANA_HOST-mngt | cut -d " " -f 1)
ALERTMANAGER_IP=$(cat /etc/hosts | grep $ALERTMANAGER_HOST-mngt | cut -d " " -f 1)

date                    | tee -a /var/log/ceph/ip.log
echo "$GRAFANA_HOST     | $GRAFANA_IP"          | tee -a /var/log/ceph/ip.log
echo "$ALERTMANAGER_HOST        | $ALERTMANAGER_IP"     | tee -a /var/log/ceph/ip.log
echo "$PROMETHEUS_HOST  | $PROMETHEUS_IP"       | tee -a /var/log/ceph/ip.log

ceph config set mgr mgr/dashboard/ALERTMANAGER_API_HOST http://$ALERTMANAGER_IP:9093
ceph config set mgr mgr/dashboard/GRAFANA_API_URL https://$GRAFANA_IP:3000
ceph config set mgr mgr/dashboard/PROMETHEUS_API_HOST http://$PROMETHEUS_IP:9095
